name: Build and Analyze

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Use Node.js version specified in package.json
              run: npx nvm use

            - name: Install dependencies
              run: yarn install

            - name: Build TypeScript
              run: yarn build

            - name: Build Docker Image
              run: |
                  docker build -t project-pfa .

            - name: Run SonarQube Analysis
              uses: sonarsource/sonarqube-scanner-github-action@v1
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

            - name: Generate SonarQube report
              run: |
                  echo "SonarQube report can be found at: file://$GITHUB_WORKSPACE/sonarqube-report.html"
